import { expect, test } from "../fixtures";

// A 1×1 transparent PNG in base64 (smallest valid PNG)
const PLACEHOLDER_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==";

const MOCK_RESULTS = [
  {
    modelKey: "dalle3",
    label: "DALL-E 3",
    success: true,
    base64: PLACEHOLDER_BASE64,
    mediaType: "image/png",
  },
];

test.describe("Image Studio", () => {
  test("renders the studio page with model checkboxes and prompt textarea", async ({
    adaContext,
  }) => {
    const { page } = adaContext;

    await page.goto("/studio");

    await expect(page.getByText("Image Studio")).toBeVisible({ timeout: 15_000 });
    await expect(page.getByText("DALL-E 3")).toBeVisible();
    await expect(page.getByText("Imagen 3 Fast")).toBeVisible();
    await expect(page.getByText("Flux 1.1 Pro")).toBeVisible();
    await expect(
      page.getByPlaceholder("Describe the image you want to generate…")
    ).toBeVisible();
    await expect(page.getByRole("button", { name: "Generate" })).toBeVisible();
  });

  test("Generate button is disabled when prompt is empty", async ({
    adaContext,
  }) => {
    const { page } = adaContext;

    await page.goto("/studio");
    await expect(
      page.getByRole("button", { name: "Generate" })
    ).toBeDisabled({ timeout: 10_000 });
  });

  test("submitting a prompt calls the generate API and displays an image", async ({
    adaContext,
  }) => {
    const { page } = adaContext;

    await page.route("**/api/studio/generate", async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ results: MOCK_RESULTS }),
      });
    });

    await page.goto("/studio");

    const promptTextarea = page.getByPlaceholder(
      "Describe the image you want to generate…"
    );
    await expect(promptTextarea).toBeVisible({ timeout: 15_000 });
    await promptTextarea.fill("A red sunset over the ocean");

    const generateButton = page.getByRole("button", { name: "Generate" });
    await expect(generateButton).toBeEnabled();
    await generateButton.click();

    // Image result card should appear
    const resultImage = page.getByRole("img", { name: /Generated by DALL-E 3/i });
    await expect(resultImage).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText("DALL-E 3").first()).toBeVisible();
    await expect(page.getByRole("button", { name: /download/i })).toBeVisible();
  });

  test("shows error message when generation API fails", async ({
    adaContext,
  }) => {
    const { page } = adaContext;

    await page.route("**/api/studio/generate", async (route) => {
      await route.fulfill({
        status: 429,
        contentType: "application/json",
        body: JSON.stringify({ error: "Rate limit exceeded", cause: "You have reached your daily image generation limit." }),
      });
    });

    await page.goto("/studio");

    const promptTextarea = page.getByPlaceholder(
      "Describe the image you want to generate…"
    );
    await expect(promptTextarea).toBeVisible({ timeout: 15_000 });
    await promptTextarea.fill("A stormy sea at night");

    await page.getByRole("button", { name: "Generate" }).click();

    await expect(
      page.getByText("You have reached your daily image generation limit.")
    ).toBeVisible({ timeout: 15_000 });
  });

  test("can toggle model selection", async ({ adaContext }) => {
    const { page } = adaContext;

    await page.goto("/studio");
    await expect(page.getByText("Image Studio")).toBeVisible({ timeout: 15_000 });

    // DALL-E 3 is checked by default — uncheck it
    const dalleLabel = page.locator("label").filter({ hasText: "DALL-E 3" });
    const dalleCheckbox = dalleLabel.locator("input[type='checkbox']");
    await expect(dalleCheckbox).toBeChecked();
    await dalleCheckbox.uncheck();
    await expect(dalleCheckbox).not.toBeChecked();

    // Check Imagen 3 Fast
    const imagenLabel = page.locator("label").filter({ hasText: "Imagen 3 Fast" });
    const imagenCheckbox = imagenLabel.locator("input[type='checkbox']");
    await imagenCheckbox.check();
    await expect(imagenCheckbox).toBeChecked();
  });
});
